name: Jest with Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install # using yarn instead of npm
    - name: Run Jest tests with Playwright
      run: yarn test # This will run the jest tests which internally use playwright for e2e testing
    # (Optional) If you have any artifacts or reports you want to upload, you can use the following:
    #- uses: actions/upload-artifact@v3
    #  if: always()
    #  with:
    #    name: jest-playwright-report
    #    path: path-to-your-report/
    #    retention-days: 30 
