name: Jest with Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - name: Install dependencies
      run: yarn install # using yarn instead of npm
    - name: Install Playwright dependencies
      run: sudo apt-get install -y libgtk-3-0 libnss3 libasound2 libgbm-dev
    - name: Run Jest tests with Playwright
      run: yarn test # This will run the jest tests which internally use playwright for e2e testing
    # (Optional) If you have any artifacts or reports you want to upload, you can use the following:
    #- uses: actions/upload-artifact@v2
    #  if: always()
    #  with:
    #    name: jest-playwright-report
    #    path: path-to-your-report/
    #    retention-days: 30
